// Maps common IANA timezone identifiers to country names in the form most
// likely to appear in scraped job-board location strings (substring match).
// Not exhaustive — covers the heaviest-populated zones across regions.

export const TIMEZONE_COUNTRY_MAP: Readonly<Record<string, string>> = {
  // South America
  'America/Guayaquil': 'Ecuador',
  'America/Lima': 'Peru',
  'America/Bogota': 'Colombia',
  'America/Caracas': 'Venezuela',
  'America/La_Paz': 'Bolivia',
  'America/Asuncion': 'Paraguay',
  'America/Montevideo': 'Uruguay',
  'America/Santiago': 'Chile',
  'America/Argentina/Buenos_Aires': 'Argentina',
  'America/Argentina/Cordoba': 'Argentina',
  'America/Argentina/Mendoza': 'Argentina',
  'America/Sao_Paulo': 'Brazil',
  'America/Bahia': 'Brazil',
  'America/Fortaleza': 'Brazil',
  'America/Manaus': 'Brazil',
  'America/Recife': 'Brazil',
  'America/Cayenne': 'French Guiana',
  'America/Paramaribo': 'Suriname',
  'America/Georgetown': 'Guyana',

  // Central America & Caribbean
  'America/Mexico_City': 'Mexico',
  'America/Monterrey': 'Mexico',
  'America/Cancun': 'Mexico',
  'America/Tijuana': 'Mexico',
  'America/Guatemala': 'Guatemala',
  'America/El_Salvador': 'El Salvador',
  'America/Tegucigalpa': 'Honduras',
  'America/Managua': 'Nicaragua',
  'America/Costa_Rica': 'Costa Rica',
  'America/Panama': 'Panama',
  'America/Havana': 'Cuba',
  'America/Santo_Domingo': 'Dominican Republic',
  'America/Port-au-Prince': 'Haiti',
  'America/Jamaica': 'Jamaica',
  'America/Puerto_Rico': 'Puerto Rico',

  // North America
  'America/New_York': 'USA',
  'America/Detroit': 'USA',
  'America/Chicago': 'USA',
  'America/Denver': 'USA',
  'America/Phoenix': 'USA',
  'America/Los_Angeles': 'USA',
  'America/Anchorage': 'USA',
  'America/Honolulu': 'USA',
  'America/Indianapolis': 'USA',
  'America/Boise': 'USA',
  'America/Toronto': 'Canada',
  'America/Vancouver': 'Canada',
  'America/Edmonton': 'Canada',
  'America/Winnipeg': 'Canada',
  'America/Halifax': 'Canada',
  'America/St_Johns': 'Canada',

  // Europe
  'Europe/London': 'UK',
  'Europe/Dublin': 'Ireland',
  'Europe/Lisbon': 'Portugal',
  'Europe/Madrid': 'Spain',
  'Europe/Paris': 'France',
  'Europe/Brussels': 'Belgium',
  'Europe/Amsterdam': 'Netherlands',
  'Europe/Luxembourg': 'Luxembourg',
  'Europe/Berlin': 'Germany',
  'Europe/Zurich': 'Switzerland',
  'Europe/Vienna': 'Austria',
  'Europe/Rome': 'Italy',
  'Europe/Copenhagen': 'Denmark',
  'Europe/Stockholm': 'Sweden',
  'Europe/Oslo': 'Norway',
  'Europe/Helsinki': 'Finland',
  'Europe/Warsaw': 'Poland',
  'Europe/Prague': 'Czech Republic',
  'Europe/Budapest': 'Hungary',
  'Europe/Bucharest': 'Romania',
  'Europe/Sofia': 'Bulgaria',
  'Europe/Athens': 'Greece',
  'Europe/Istanbul': 'Turkey',
  'Europe/Moscow': 'Russia',
  'Europe/Kiev': 'Ukraine',

  // Africa
  'Africa/Cairo': 'Egypt',
  'Africa/Lagos': 'Nigeria',
  'Africa/Nairobi': 'Kenya',
  'Africa/Johannesburg': 'South Africa',
  'Africa/Casablanca': 'Morocco',
  'Africa/Tunis': 'Tunisia',
  'Africa/Algiers': 'Algeria',
  'Africa/Accra': 'Ghana',

  // Middle East
  'Asia/Dubai': 'UAE',
  'Asia/Riyadh': 'Saudi Arabia',
  'Asia/Qatar': 'Qatar',
  'Asia/Kuwait': 'Kuwait',
  'Asia/Tel_Aviv': 'Israel',
  'Asia/Jerusalem': 'Israel',
  'Asia/Beirut': 'Lebanon',
  'Asia/Tehran': 'Iran',

  // Asia
  'Asia/Karachi': 'Pakistan',
  'Asia/Kolkata': 'India',
  'Asia/Calcutta': 'India',
  'Asia/Colombo': 'Sri Lanka',
  'Asia/Dhaka': 'Bangladesh',
  'Asia/Bangkok': 'Thailand',
  'Asia/Singapore': 'Singapore',
  'Asia/Kuala_Lumpur': 'Malaysia',
  'Asia/Jakarta': 'Indonesia',
  'Asia/Manila': 'Philippines',
  'Asia/Ho_Chi_Minh': 'Vietnam',
  'Asia/Hong_Kong': 'Hong Kong',
  'Asia/Taipei': 'Taiwan',
  'Asia/Shanghai': 'China',
  'Asia/Tokyo': 'Japan',
  'Asia/Seoul': 'South Korea',

  // Oceania
  'Australia/Sydney': 'Australia',
  'Australia/Melbourne': 'Australia',
  'Australia/Brisbane': 'Australia',
  'Australia/Perth': 'Australia',
  'Australia/Adelaide': 'Australia',
  'Pacific/Auckland': 'New Zealand',
};
