from hiresense.scheduler.domain.ports import JobRunRepository, JobToggleRepository


def test_ports_are_runtime_checkable_protocols():
    # Protocols expose their methods; a duck-typed object satisfies isinstance.
    class _Runs:
        def record(self, run): ...
        def recent(self, job_name, limit): ...
        def latest(self, job_name): ...

    class _Toggles:
        def is_enabled(self, job_name, default): ...
        def set_enabled(self, job_name, enabled): ...
        def all_states(self): ...

    assert isinstance(_Runs(), JobRunRepository)
    assert isinstance(_Toggles(), JobToggleRepository)
