from __future__ import annotations

import uuid
from typing import Protocol

from hiresense.applications.domain.models import (
    ApplicationCvOptimization,
    ApplicationInterviewPrep,
    ApplicationJobSnapshot,
    ApplicationMatch,
)


class ApplicationRepositoryPort(Protocol):
    # Job snapshot (1:1)
    def create_snapshot(self, snapshot: ApplicationJobSnapshot) -> ApplicationJobSnapshot: ...
    def get_snapshot(self, application_id: uuid.UUID) -> ApplicationJobSnapshot | None: ...
    def save_snapshot(self, snapshot: ApplicationJobSnapshot) -> ApplicationJobSnapshot: ...

    # Matches (1:N)
    def create_match(self, match: ApplicationMatch) -> ApplicationMatch: ...
    def list_matches(self, application_id: uuid.UUID) -> list[ApplicationMatch]: ...
    def get_latest_match(self, application_id: uuid.UUID) -> ApplicationMatch | None: ...
    def get_match(self, match_id: uuid.UUID) -> ApplicationMatch | None: ...

    # CV optimizations (1:N)
    def create_optimization(self, opt: ApplicationCvOptimization) -> ApplicationCvOptimization: ...
    def list_optimizations(self, application_id: uuid.UUID) -> list[ApplicationCvOptimization]: ...
    def get_latest_optimization(self, application_id: uuid.UUID) -> ApplicationCvOptimization | None: ...

    # Interview preps (1:N)
    def create_interview_prep(self, prep: ApplicationInterviewPrep) -> ApplicationInterviewPrep: ...
    def list_interview_preps(self, application_id: uuid.UUID) -> list[ApplicationInterviewPrep]: ...
    def get_latest_interview_prep(self, application_id: uuid.UUID) -> ApplicationInterviewPrep | None: ...
