from __future__ import annotations

import uuid
from typing import Any, Protocol

from hiresense.applications.domain.models import (
    ApplicationCoverLetter,
    ApplicationCvOptimization,
    ApplicationInterviewPrep,
    ApplicationJobSnapshot,
    ApplicationMatch,
)


class ApplicationRepositoryPort(Protocol):
    # Job snapshot (1:1)
    def create_snapshot(self, snapshot: ApplicationJobSnapshot) -> ApplicationJobSnapshot: ...
    def get_snapshot(self, application_id: uuid.UUID) -> ApplicationJobSnapshot | None: ...
    def save_snapshot(self, snapshot: ApplicationJobSnapshot) -> ApplicationJobSnapshot: ...

    # Matches (1:N)
    def create_match(self, match: ApplicationMatch) -> ApplicationMatch: ...
    def list_matches(self, application_id: uuid.UUID) -> list[ApplicationMatch]: ...
    def get_latest_match(self, application_id: uuid.UUID) -> ApplicationMatch | None: ...
    def get_match(self, match_id: uuid.UUID) -> ApplicationMatch | None: ...

    # CV optimizations (1:N)
    def create_optimization(self, opt: ApplicationCvOptimization) -> ApplicationCvOptimization: ...
    def list_optimizations(self, application_id: uuid.UUID) -> list[ApplicationCvOptimization]: ...
    def get_latest_optimization(self, application_id: uuid.UUID) -> ApplicationCvOptimization | None: ...
    def get_optimization(self, optimization_id: uuid.UUID) -> ApplicationCvOptimization | None: ...

    # Interview preps (1:N)
    def create_interview_prep(self, prep: ApplicationInterviewPrep) -> ApplicationInterviewPrep: ...
    def list_interview_preps(self, application_id: uuid.UUID) -> list[ApplicationInterviewPrep]: ...
    def get_latest_interview_prep(self, application_id: uuid.UUID) -> ApplicationInterviewPrep | None: ...

    # Cover letters (1:N)
    def create_cover_letter(self, letter: ApplicationCoverLetter) -> ApplicationCoverLetter: ...
    def list_cover_letters(self, application_id: uuid.UUID) -> list[ApplicationCoverLetter]: ...
    def get_latest_cover_letter(self, application_id: uuid.UUID) -> ApplicationCoverLetter | None: ...
    def get_cover_letter(self, cover_letter_id: uuid.UUID) -> ApplicationCoverLetter | None: ...
    def list_all_cover_letters_with_context(self) -> list[dict[str, Any]]: ...
