from hiresense.inbox.domain.ports import DetectedSignalRepository, InboxReaderPort


def test_ports_are_runtime_checkable():
    class _Reader:
        def fetch_unseen(self): ...

    class _Repo:
        def add(self, signal): ...
        def list(self, state=None): ...
        def get(self, id): ...
        def set_state(self, id, state): ...
        def exists_message_id(self, message_id): ...

    assert isinstance(_Reader(), InboxReaderPort)
    assert isinstance(_Repo(), DetectedSignalRepository)
